import type { Metadata } from 'next';
import { fonts } from '@/shared/lib';
import '@/app/styles/style.scss';
import { Header } from '@/widgets/header';

export const metadata: Metadata = {
  title: 'GeoDistribution',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fonts.raleway.className}>
        <Header />
        {children}
        <footer />
      </body>
    </html>
  );
}
