import type { Metadata } from 'next';
import { fonts } from '@/app/shared/lib';
import '@/app/styles/style.scss';
import { getLocale, getMessages } from 'next-intl/server';
import { NextIntlClientProvider } from 'next-intl';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { Header } from '@/app/widgets/header/ui/header';
import { Footer } from '@/app/widgets/footer/ui/footer';

export const metadata: Metadata = {
  title: 'GeoDistribution',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body className={fonts.raleway.className}>
        <NextIntlClientProvider messages={messages}>
          <AntdRegistry>
            <Header />
            {children}
            <Footer />
          </AntdRegistry>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
